version: "3"
services: 

    server:
        build:
            context: ./server
            dockerfile: Dockerfile 
        ports:
            - 8000:8000
        volumes:
            - ./server:/server
        command: >
            bash -c '
            python manage.py runserver 0:8000 &&
            python manage.py makemigrations &&
            python manage.py migrate'
