# Generated by Django 3.0.8 on 2021-06-28 06:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.IntegerField(default=999)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resume/')),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InitCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_no', models.IntegerField()),
                ('cat_text', models.CharField(max_length=255)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
            ],
        ),
        migrations.CreateModel(
            name='Json',
            fields=[
                ('json_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('json', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('mturk_id', models.TextField()),
                ('consentAgreed', models.BooleanField(default=False)),
                ('instrEnded', models.BooleanField(default=False)),
                ('joinTime', models.DateTimeField(auto_now_add=True)),
                ('consentEndTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('instrEndTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_text', models.CharField(max_length=255)),
                ('made_at', models.IntegerField(default=9999, null=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_text', models.CharField(max_length=255)),
                ('subcat_description', models.CharField(max_length=255)),
                ('made_at', models.IntegerField(default=9999, null=True)),
                ('usercat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCat')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logTime', models.DateTimeField(auto_now_add=True)),
                ('imageID', models.IntegerField(default=-1)),
                ('boxIDs', models.TextField(default=[], validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('label', models.CharField(max_length=255)),
                ('behavior', models.CharField(choices=[('NL', 'NULL'), ('SB', 'SelectBox'), ('UB', 'UnselectBox'), ('UA', 'UnselectAllBox'), ('CL', 'ChooseLabel'), ('RA', 'RemoveAnnotation'), ('RL', 'RemoveAllAnnotation'), ('RI', 'ReadInstruction'), ('SU', 'Submit')], default='NL', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageID', models.IntegerField()),
                ('groupID', models.IntegerField()),
                ('boxIDs', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('label', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='InitSubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_no', models.IntegerField()),
                ('subcat_text', models.CharField(max_length=255)),
                ('subcat_description', models.CharField(max_length=255)),
                ('initcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InitCat')),
            ],
        ),
        migrations.CreateModel(
            name='DefAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes_id', models.TextField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('confidence', models.BooleanField(default=True, null=True)),
                ('is_alive', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserCat')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserSubcat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes_id', models.TextField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('is_alive', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserCat')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserSubcat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
