# Generated by Django 3.0.8 on 2020-11-13 14:13

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageID', models.IntegerField()),
                ('boxIDs', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('behavior', models.CharField(choices=[('NL', 'NULL'), ('SB', 'SelectBox'), ('UB', 'UnselectBox'), ('UA', 'UnselectAllBox'), ('CL', 'ChooseLabel'), ('RA', 'RemoveAnnotation'), ('RL', 'RemoveAllAnnotation'), ('RI', 'ReadInstruction'), ('SU', 'Submit')], default='NL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.TextField()),
                ('consentAgreed', models.BooleanField(default=False)),
                ('step', models.IntegerField(default=1)),
                ('joinTime', models.DateTimeField(auto_now_add=True)),
                ('consentEndTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('instrEndTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
