# Generated by Django 3.0.8 on 2021-06-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mturk_id',
        ),
    ]
