# Generated by Django 3.0.8 on 2020-07-06 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField()),
                ('child', models.IntegerField()),
                ('left_top_x', models.IntegerField(validators=[django.core.validators.MaxValueValidator(256), django.core.validators.MinValueValidator(0)])),
                ('left_top_y', models.IntegerField(validators=[django.core.validators.MaxValueValidator(256), django.core.validators.MinValueValidator(0)])),
                ('width', models.IntegerField(validators=[django.core.validators.MaxValueValidator(256), django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(256), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='box',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
