# Generated by Django 3.0.8 on 2020-11-17 16:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201117_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='boxIDs',
            field=models.TextField(default=[], validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
