# Generated by Django 3.0.8 on 2021-06-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210629_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType'),
        ),
    ]
