# Generated by Django 3.0.8 on 2020-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200706_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
