# Generated by Django 3.0.8 on 2020-08-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_is_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
