# Generated by Django 3.0.8 on 2020-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='imageID',
            field=models.IntegerField(default=-1),
        ),
    ]
