# Generated by Django 3.0.8 on 2021-06-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210630_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubcat',
            name='usercat',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.InitCat'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.InitSubCat'),
        ),
        migrations.AlterField(
            model_name='defannotation',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.InitCat'),
        ),
        migrations.AlterField(
            model_name='defannotation',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.InitSubCat'),
        ),
        migrations.DeleteModel(
            name='UserCat',
        ),
        migrations.DeleteModel(
            name='UserSubcat',
        ),
    ]
