# Generated by Django 3.0.8 on 2021-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210630_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dropout',
            field=models.BooleanField(default=False),
        ),
    ]
