# Generated by Django 3.0.8 on 2020-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201117_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='label',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
