# Generated by Django 3.0.8 on 2020-08-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_box_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
