# Generated by Django 3.0.8 on 2021-04-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_log_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=50)),
                ('className', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclassName', models.CharField(max_length=100)),
                ('decription', models.CharField(max_length=200)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SubClass')),
            ],
        ),
    ]
