# Generated by Django 3.2.1 on 2021-05-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_class_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class'),
        ),
    ]
