# Generated by Django 3.2.1 on 2021-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_subclass_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='username',
            field=models.CharField(default='initial', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subclass',
            name='username',
            field=models.CharField(default='initial', max_length=50),
            preserve_default=False,
        ),
    ]
