# Generated by Django 3.0.8 on 2021-05-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210506_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.IntegerField()),
                ('doc_id', models.CharField(max_length=255)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
            ],
        ),
        migrations.CreateModel(
            name='InitCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_no', models.IntegerField()),
                ('cat_text', models.CharField(max_length=255)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
            ],
        ),
        migrations.CreateModel(
            name='InitSubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_no', models.IntegerField()),
                ('subcat_text', models.CharField(max_length=255)),
                ('subcat_description', models.CharField(max_length=255)),
                ('initcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InitCat')),
            ],
        ),
        migrations.CreateModel(
            name='UserCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_no', models.IntegerField()),
                ('cat_text', models.CharField(max_length=255)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_no', models.IntegerField()),
                ('subcat_text', models.CharField(max_length=255)),
                ('subcat_description', models.CharField(max_length=255)),
                ('usercat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserCat')),
            ],
        ),
        migrations.RemoveField(
            model_name='subclass',
            name='className',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='SubClass',
        ),
        migrations.AddField(
            model_name='annotation',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.UserSubcat'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
