# Generated by Django 3.0.8 on 2021-05-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210511_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='annotation',
            name='doc_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='box_id',
            field=models.IntegerField(default=1),
        ),
    ]
