# Generated by Django 3.0.8 on 2021-05-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mturk_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='status',
            name='doctype',
        ),
        migrations.RemoveField(
            model_name='status',
            name='start',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_image_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='step',
        ),
        migrations.AddField(
            model_name='status',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document'),
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_no',
            field=models.IntegerField(default=999),
        ),
    ]
