# Generated by Django 3.0.8 on 2021-05-23 23:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210511_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='status',
            new_name='is_alive',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='box_id',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='doc_no',
        ),
        migrations.AddField(
            model_name='annotation',
            name='boxes_id',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
