# Generated by Django 3.0.8 on 2021-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210614_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Json',
            fields=[
                ('json_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('json', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='box_info',
        ),
        migrations.RemoveField(
            model_name='image',
            name='count_assigned',
        ),
    ]
